config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions
  resources :drumpads
  resources :sounds

  root :to => "pages#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drumpad.rb
class Drumpad < ApplicationRecord
  has_many :sounds
end

app/models/sound.rb
class Sound < ApplicationRecord
   belongs_to :drumpad, optional:true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :uniqueness => true, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token #required for API's
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil if @current_user.nil?
  end

  def check_for_login
    redirect_to new_session_path unless @current_user.present?
  end

  # Prevents attempts to log in while another user is logged in
  def check_for_no_login
    redirect_to user_path(@current_user.id) unless @current_user.nil?
  end

  # Prevents attempts to access other user's accounts
  def check_for_specific_user
    redirect_to user_path(@current_user.id) unless @current_user.id == params[:id].to_i
  end
end

app/controllers/drumpads_controller.rb
class DrumpadsController < ApplicationController
    before_action :check_for_login, except: [:index]

  def index
    @drumpads = Drumpad.all.sort_by { |drumpad| drumpad.id}
  end

  def new
    @drumpad = Drumpad.new
  end

  def create
    drumpad = Drumpad.create drumpad_params
    redirect_to drumpad_path(drumpad.id)
  end

  def edit
    @drumpad = Drumpad.find params[:id]
  end

  def update
    drumpad = Drumpad.find params[:id]
    drumpad.update drumpad_params
    redirect_to drumpads_path
  end

  def show
    @drumpad = Drumpad.find params[:id];
    allSounds = Sound.all.sort_by{ |sound| sound.id}
    @sounds = []
    allSounds.each do |sound|
      @sounds.push(sound)  if sound.drumpad_id == params[:id].to_i
    end
  end

  def destroy
    drumpad = Drumpad.find params[:id]
    drumpad.destroy
    redirect_to drumpads_path
  end

  private
  def drumpad_params
    params.require(:drumpad).permit(:name, :color)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :check_for_no_login, except: [:destroy]
  before_action :check_for_login, only: [:destroy]

  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid Email Or Password"
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  before_action :check_for_login, except: [:index]

  def index
    @sounds = Sound.all.sort_by{ |sound| sound.id }
  end

  def new
    @sound = Sound.new params[:id]
  end

  def create
    sound = Sound.create sound_params
    # sound = Sound.create sound_params
    drumpad_id = sound.drumpad_id
    # if params[:file].present?
    #   req = Cloudinary::Uploader.upload(params[:file], :resource_type => "auto")
    #   sound.url = req["public_id"] # this is an URL
    #   sound.save
    # end
    redirect_to sound_path(sound)
  end

  def update
    sound = Sound.find params[:id]
    sound.update sound_params
    # if params[:file].present?
    #   req = Cloudinary::Uploader.upload(Rails.root + params[:file], :resource_type => "auto")
    #   sound.url = req["public_id"]
    # end
    # sound.save
    redirect_to request.referrer
  end

  def show
    @sound = Sound.find params[:id]
  end

  def destroy
    sound = Sound.find params[:id]
    drumpad_id = sound.drumpad_id
    sound.destroy
    redirect_to drumpad_path(drumpad_id)
  end

  private
  def sound_params
    params.require(:sound).permit(:name, :key_code, :key_trigger, :url, :drumpad_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_login
  before_action :check_for_specific_user, only: [:show, :update]

  def index
    @users = User.all
  end

  def new
  end

  def update
    user = User.find params[:id]
    user.update user_params
    redirect_to user_path(user.id)
  end

  def show
    @user = User.find params[:id]
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drumpads_helper.rb
module DrumpadsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drumpads/_form.html.erb
<div class="section-group">
  <%= form_for @drumpad do |f| %>
      <section>
        <p>
          <%= f.label :name %>
          <%= f.text_field :name, :required => true, :placeholder => "New Key Set" %>
        </p>
        <p>
          <%= f.label :color %>
          <%= f.text_field :color %>
        </p>
        <%= f.submit "Submit" %>
      </section>

  <% end %>

</div>

app/views/drumpads/edit.html.erb
<h2>Edit <%= @drumpad.name %></h2>

<p>Use this form to edit <%= @drumpad.name %>'s details.</p>
<%= link_to "You can add new sounds here", new_sound_path %>

<%= render :partial => "form" %>

app/views/drumpads/index.html.erb
<h2>Key Sets List</h2>

<% @drumpads.each do |drumpad| %>
    <p>
      <%= link_to drumpad.name, drumpad_path(drumpad.id) %>
      <% if @current_user.present? %>
        <%= link_to "Edit", edit_drumpad_path(drumpad.id), :class => "edit" %>
        <%= link_to "Delete", drumpad_path(drumpad.id), :method => "delete", :class => "delete" %>
      <% end %>  
    </p>

<% end %>

app/views/drumpads/new.html.erb
<h2>Create A New Key Set</h2>

<p>Use this form to create a new set of keys.</p>

<%= render :partial => "form" %>

app/views/drumpads/show.html.erb
<%= link_to "Click Here To Add More Sounds", new_sound_path %>

<h2><%= @drumpad.name %> (<%= @drumpad.color.capitalize %>)</h2>

<% @sounds.each do |sound| %>
 <div class="song-info">
   <h3><%= link_to sound.name, sound_path(sound.id) %> </h3>
   <p><strong>Key Code</strong> <%= sound.key_code %> </p>
   <p><strong>Key Trigger</strong> <%= sound.key_trigger %> </p>
   <p><span class="url"><%= sound.url %></span></p>
 </div>
<% end %>

<p><%= link_to "Delete Key Set", drumpad_path(@drumpad.id), :method => "delete", :class => "delete" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drum Machine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to "Home", root_path %> <!--Visible to everyone -->
      <% if @current_user.nil? %>
        <%= link_to "Log In", new_session_path %><!-- Only Visible When Not logged in -->
        <%= link_to "View Key Sets", drumpads_path %> <!--Visible to everyone, but listed here to maintain order -->
        <%= link_to "View Sounds", sounds_path %> <!--Visible to everyone, but listed here to maintain order -->
      <% else %>
        <%= link_to "View Your Details", user_path(@current_user.id) %><!--Only Visible When logged in -->
        <%= link_to "Add A New Key Set", new_drumpad_path %> <!--Visible to all logged in users -->
        <%= link_to "View Key Sets", drumpads_path %> <!--Visible to everyone, but listed here to maintain order -->
        <%= link_to "Add A New Sound", new_sound_path %> <!--Visible to all logged in users -->
        <%= link_to "View Sounds", sounds_path %> <!--Visible to everyone, but listed here to maintain order -->
        <%= link_to "View Users", users_path %> <!--Visible to all logged in users -->
        <%= link_to "Log Out", session_path(@current_user.id), :method => "delete" %>
      <% end %>
    </nav>
    <h1>Drum Machine Admin Site</h1>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<p>Welcome to the Drum Machine Admin Site.</p>

<% if @current_user.nil? %>
  <p>Log in to start edit the key sets and sounds.</p>
  <%= link_to "Log In", new_session_path %>
<% else %>
  <p> Use the buttons below to add key sets and sounds.</p>
  <%= link_to "Add A New Key Set", new_drumpad_path %>
  <%= link_to "Add A New Sound", new_sound_path %>
<% end %>

app/views/sounds/_form.html.erb
<div class="section-group">
  <%= form_for @sound do |f| %>
    <!-- All the properties are required, since a sound must have all these properties to be usable -->
      <section>
        <p>
          <%= f.label :name %>
          <%= f.text_field :name, :required => true, :placeholder => "Heater-1" %>
        </p>
        <p>
          <%= f.label :key_code %>
          <%= f.number_field :key_code, :required => true %>
        </p>
        <p>
          <%= f.label :key_trigger %>
          <%= f.text_field :key_trigger, :required => true %>
        </p>
        <p>
          <%= f.label "URL" %>
          <%= f.text_field :url, :required => true %><!--Use cl_upload :url, :resource_type => "auto" for Cloudinary-->
        </p>
        <p>
          <%= f.label "Key Set" %>
          <%= f.select :drumpad_id, Drumpad.pluck(:name, :id), :required => true %>
        </p>

          <%= f.submit "Submit" %>
      </section>

  <% end %>

</div>

app/views/sounds/index.html.erb
<h2>Sound List</h2>

<p>These are all the sounds that have been created for the Drum Machine app.</p>

<p id="sound-list">
  <% @sounds.each do |sound| %>
    <%= link_to sound.name, sound_path(sound.id) %>
  <% end %>
</p>

app/views/sounds/new.html.erb
<h1>Create A New Sound</h1>

<p>Use this form to create a new sound.</p>

<%= render :partial => "form" %>

app/views/sounds/show.html.erb
<h2><%= @sound.name %></h2>

<p><strong>Key Code: </strong><%= @sound.key_code %><strong>Key Trigger: </strong><%= @sound.key_trigger %></p>
<p><strong>URL:</strong><%= @sound.url %></p>
<p><%= link_to "View All Key Set Sounds", drumpad_path(@sound.drumpad_id) %></p>

<h3>Edit Sound </h3>

<%= render :partial => "form" %>

<p><%= button_to "Delete Sound", @sound, :method => "delete", :class => "delete" %></p>

app/views/users/index.html.erb
<h2>Users List</h2>

<p>The following people can use this site to create, edit and delete drumpads and sounds.</p>

<% @users.each do |user| %>
  <p>
    <strong> Name: </strong><%= user.name %>,<strong> Email: </strong><%= user.email %>
  </p>
<% end %>

app/views/users/show.html.erb
<h2>View Your Details</h2>

<p><strong> Name: </strong><%= @user.name %></p>
<p><strong> Email: </strong><%= @user.email %></p>

<h2>Edit Your Details</h2>

<div class="section-group">
  <%= form_for @user do |f| %>
      <section>
        <p>
          <strong><%= f.label :name %></strong>
          <%= f.text_field :name, :required => true %>
        </p>
        <p>
          <strong><%= f.label :email %></strong>
          <%= f.email_field :email, :required => true %>
        </p>

        <%= f.submit "Edit Details" %>
      </section>

  <% end %>

</div>